#!/bin/bash -e

. ~/set_cpu_count

echo "RK with \$(nproc):          $(nproc)"
echo "OMP_NUM_THREADS:            $OMP_NUM_THREADS"
echo "CCX_NPROC_EQUATION_SOLVER:  $CCX_NPROC_EQUATION_SOLVER"
echo "CCX_NPROC_RESULTS:          $CCX_NPROC_RESULTS"
echo "NUMBER_OF_CPUS:             $NUMBER_OF_CPUS"

