#!/bin/bash -xe

# setup env
.  ~/ccx_env

#
[ -f "Mesh_1.inp" ] && rm -f Mesh_1.inp
unv2ccx Mesh_1.unv

#
JobName=case

#
rm -f spooles.out ${JobName}.12d ${JobName}.cvg ${JobName}.dat ${JobName}.frd ${JobName}.sta ${JobName}.vtu
ccx ${JobName}
ccx2paraview ${JobName}.frd vtu
