#!/bin/bash -xe

# setup env
.  ~/ccx_env
./Allclean

#
[ -f "Mesh_1.inp" ] && rm -f Mesh_1.inp
[ -f "Mesh_1.unv" ] || xz -d Mesh_1.unv.xz

unv2ccx Mesh_1.unv

#
JobName=case

ccx ${JobName}
ccx2paraview ${JobName}.frd vtu

